version: '3'

services:
  mongo:
    image: mongo
    hostname: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: user1
      MONGO_INITDB_ROOT_PASSWORD: pass1
    networks:
      db-jwt-auth-app:
    volumes:
      - mongo_data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user1
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass1
      ME_CONFIG_MONGODB_URL: mongodb://user1:pass1@mongo:27017/
    depends_on:
      - mongo
    networks:
      db-jwt-auth-app:

networks:
  db-jwt-auth-app:
volumes:
  mongo_data: